### ISSUE TITLE
cd on folder with space don't work

### ISSUE THREAD

**Issue by gabriel-del** [fisherman/spin#16]
cd 'System Volume Information'
works, but
replay cd 'System Volume Information'
don't work, neither
replay cd System\ Volume\ Information/

erro: bash: line 2: cd: too many arguments

**Comment by ammgws** [comment]
I think you need to double quote it so after fish eats one set of quotes, the other set remains for bash

**Comment by gabriel-del** [comment]
it didn't work either.

replay cd ""System Volume Information""
replay cd "'System Volume Information'"
replay cd \"System Volume Information\"
replay cd "\"System Volume Information\""
replay cd ''System Volume Information''


Everything giver the error:
bash: line 2: cd: too many arguments
or
cd: The directory “System” does not exist

**Comment by ammgws** [comment]
Try single quotes on the outside

**Comment by gabriel-del** [comment]
replay cd '"System Volume Information"'
cd: The directory “System” does not exist

**Comment by gabriel-del** [comment]
oh, I get it, it's necessary to change $value to \\"$value\\" on line 34.
I opened a pull request.

https://github.com/jorgebucaran/replay.fish/pull/17
