### ISSUE TITLE
fisher: cannot connect to server -- looking in ~/.cache/fisher/github.com/jorgebucaran/fish-bax

### ISSUE THREAD

**Issue by tsdh** [fisherman/spin#8]
I've installed bax through fisher and noticed that this message is issued whenever i run `fisher` to update all installed fish packages.  I'm pretty sure this message has started popping up rather recently.  What's the meaning of that message?

I'm running fish 3.1.2 and bax 1.0.0.

**Comment by jorgebucaran** [comment]
@tsdh Fisher 3.1.2 tries to install plugins from the `master` branch, but I recently changed Bax default branch to `main`, so  Fisher can't find it and tries to install it from the cache. The latest Fisher uses the repository's HEAD instead. Please upgrade with ~~`fisher self-update`~~ `fisher update`.

**Comment by tsdh** [comment]
That's it, thanks!
